# Site settings
# in the templates available like {{ site.myvariable }}.
title: Dhanvi's Healthy Bites
email: dips@dhealthybites.com
brand: Dhanavi's Healthy Bites
headline: Healthy cooked food you would like to treat yourself with.
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.dhealthybites.com" # the base hostname & protocol for your site
copyright: 2016 Dhanvi Healthy Bites. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
# snapwidget: 247552

# Contacts
email: dips@dhealthybites.com
phone: +919011967844

# Tracking
googleAnalitycsID: UA-104499156-1

